// <auto-generated />
using System;
using AutoPost_Bot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoPost_Bot.Migrations
{
    [DbContext(typeof(PostsContext))]
    [Migration("20251112195829_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("AutoPost_Bot.Models.BotModel", b =>
                {
                    b.Property<Guid>("BotId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BotId")
                        .HasName("Bot_Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_Bots_Token");

                    b.ToTable("Bots");
                });

            modelBuilder.Entity("AutoPost_Bot.Models.GroupModel", b =>
                {
                    b.Property<long>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId")
                        .HasName("Group_Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("AutoPost_Bot.Models.PostModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BotId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Days")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostText")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepeatDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepeatHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepeatMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("Post_Id");

                    b.HasIndex("BotId");

                    b.HasIndex("GroupId");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_Posts_Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("BotModelGroupModel", b =>
                {
                    b.Property<Guid>("BotsBotId")
                        .HasColumnType("TEXT");

                    b.Property<long>("GroupsGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BotsBotId", "GroupsGroupId");

                    b.HasIndex("GroupsGroupId");

                    b.ToTable("BotGroups", (string)null);
                });

            modelBuilder.Entity("AutoPost_Bot.Models.PostModel", b =>
                {
                    b.HasOne("AutoPost_Bot.Models.BotModel", "Bot")
                        .WithMany("Posts")
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoPost_Bot.Models.GroupModel", "Group")
                        .WithMany("Posts")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Bot");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("BotModelGroupModel", b =>
                {
                    b.HasOne("AutoPost_Bot.Models.BotModel", null)
                        .WithMany()
                        .HasForeignKey("BotsBotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoPost_Bot.Models.GroupModel", null)
                        .WithMany()
                        .HasForeignKey("GroupsGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoPost_Bot.Models.BotModel", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("AutoPost_Bot.Models.GroupModel", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
