// <auto-generated />
using System;
using AutoPost_Bot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoPost_Bot.Migrations
{
    [DbContext(typeof(PostsContext))]
    partial class PostsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("AutoPost_Bot.Models.PostModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("GroupID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PostDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostText")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepeatDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepeatHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepeatMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("Post_Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_Posts_Id");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
